# go to sleep after 30 minutes (30*60*1000ms)

CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_SLEEP=y

#CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y

#The maximum brightness percentage of RGB，Reducing this value can lower the temperature of the rectifier components.(RGB的最大百分比亮度，降低可以减少发热）
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60

#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n

CONFIG_ZMK_DISPLAY=y

#缩小数值减少延迟但对轴体品质要求会更高 Reducing the value will decrease the latency, but it will also place higher demands on the switching quality. If you are confident about the quality of the switch used on the keyboard, you can try smaller values, such as 1ms - 3ms.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=3
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=3

#macos logo open this config
#CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=y

#soft off
CONFIG_ZMK_PM_SOFT_OFF=y

CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=60000

# Battery history: не записывать одинаковый уровень чаще 5 часов
CONFIG_ZMK_BATTERY_HISTORY_RECORD_SAME_LEVEL_INTERVAL_MINUTES=300

# Не выполнять принудительный flush чаще 5 часов
CONFIG_ZMK_BATTERY_HISTORY_SAVE_INTERVAL_MINUTES=300